### ISSUE TITLE
NuGet Package is out of date

### ISSUE THREAD

**Issue by a-petrovich** [spiegelp/MaterialDesignExtensions#3]
As title says, NuGet Package is out of date... Last update was month ago, and it only has Stepper realisation...
Could you please update it to current version with  "OpenDirectoryControl", "OpenFileControl" "SaveFileControl" ?

**Comment by spiegelp** [comment]
Hi, I'm planning a release as soon as the file system controls are finished. Currently I'm working on integrating them into dialogs. All of my github repositories are personal projects during my sparse free time. That's why it might take some time to finish new features. The dialog integration will probably take one further week to get a stable and sophisticated API. After that I'm going to release a new version.
