### ISSUE TITLE
File dialog icons

### ISSUE THREAD

**Issue by zEroooB** [spiegelp/MaterialDesignExtensions#30]
Hi,

it seems there is an issue with the icons in open/save file dialog. See attached screenshots.
With the demo everything works fine. (first screenshot)
Unfortunately the icons in my own project are wrong.

MaterialDesignThemes v2.5.0.1025
MaterialDesignExtensions v2.4.0

![materialdesignextensionsdemo](https://user-images.githubusercontent.com/44222219/53319654-6b3e2300-38d3-11e9-8447-583abd521562.PNG)
![openfiledialogbug](https://user-images.githubusercontent.com/44222219/53319655-6b3e2300-38d3-11e9-879a-4434f0cd8773.PNG)

**Comment by spiegelp** [comment]
@zEroooB MaterialDesignThemes updated the icons and therefore caused changes on the underlying enum. MaterialDesignExtensions was compiled against an older version of the enum. That is causing an incompatibility in the mapping (the value X in my older dll is no longer the same in the new MaterialDesignThemes version). I will prepare a release compiling against an up to date version of MaterialDesignThemes in order to solve the issue.

**Comment by spiegelp** [comment]
@zEroooB I did upload a pre-release a few moments ago.

**Comment by JackDaniel91** [comment]
Hi,

this issus occurs again. I think the underlying enum in the material design has been already changed again.

MaterialDesignThemes 2.6.0
MaterialDesignExtensions 2.6.0 and 2.7.0-a01 (issue exists in both versions)

**Comment by spiegelp** [comment]
@JackDaniel91 The enum changed again and caused a compile error in MaterialDesignExtensions. An updated release fixing the issue will be available in a few moments.
