### ISSUE TITLE
New Tabcontrol style

### ISSUE THREAD

**Issue by Coloris** [spiegelp/MaterialDesignExtensions#31]
Hello @spiegelp 

Your work to design the TabControl is looking great but is a breaking change on my app, is there any easy way to disable it ?

**Comment by spiegelp** [comment]
@Coloris I guess your problem is that the style will be applied automatically. I was beware of such kind of situation and will change this for the final release. 

If you do not need any features or fixes of the pre-release, please downgrade your dependency to the latest stable release. Otherwise you may try to add your own default style for a TabControl` based on the desired resource after the import of Material Design Extensions in your App.xaml.
