### ISSUE TITLE
FantasticFiasco MVVM Dialogs and Stepper issue

### ISSUE THREAD

**Issue by kodaniel** [spiegelp/MaterialDesignExtensions#6]
Hi!

I always use FantasticFiasco's mvvm dialog ([https://github.com/FantasticFiasco/mvvm-dialogs](url)) for my apps, but now I got an issue when I tried to open a new dialog window from a viewmodel of a Stepper's step.
The strangest thing is that the error occurs only if the stepper's layout is vertical.

I attached a sample project, please take a look.

[MaterialDesignStepperIssue.zip](https://github.com/spiegelp/MaterialDesignExtensions/files/1732284/MaterialDesignStepperIssue.zip)

**Comment by spiegelp** [comment]
Hi! 

I don't known what the exact problem is but it seems to be caused by an `ItemsControl`. Only the vertical `Stepper` uses one in its template. It seems that the view of the step is not registered by FantasticFiasco's mvvm dialog. 

I changed your code to let it be more like the stepper demo. The dialog is working now and can't tell why. Lets have a look to the changes: 
* `StepViewModel` does not inherit from `Step`, because it should only be the content of a step. 
* `MainViewModel` adds a step this way: `new Step() { Header = "Step", Content = new StepViewModel() }`
* The XAML of `MainWindow` adds a `DataTemplate` to its resources, to define `StepView` as the view for `StepViewModel`. 
* `StepView` do not need to set a `DataContext`, because this will be done automatically by WPF via the data template. 

[MaterialDesignStepperIssue_fix.zip](https://github.com/spiegelp/MaterialDesignExtensions/files/1756075/MaterialDesignStepperIssue_fix.zip)
