### ISSUE TITLE
MaterialWindow customization

### ISSUE THREAD

**Issue by SpoinkyNL** [spiegelp/MaterialDesignExtensions#64]
Hello,

I'm hoping to use MaterialDesignExtensions as a complete replacement for MahApps.Metro but one thing I'm really missing is customization on the MaterialWindow.

It would be great if there was the possibility of changing the icon template, as the icon I want to show in the title bar isn't the same as the one I want to show in the taskbar.

[MetroWindow](https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/MetroWindow.cs#L121) has IconTemplate and TitleTemplate one can override and I think it would be a useful addition to this library to implement the same.

**Comment by sofareti** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Robert Beekman <notifications@github.com> Date: 12/12/19  19:08  (GMT+03:00) To: spiegelp/MaterialDesignExtensions <MaterialDesignExtensions@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [spiegelp/MaterialDesignExtensions] MaterialWindow customization (#64) Hello,
I'm hoping to use MaterialDesignExtensions as a complete replacement for MahApps.Metro but one thing I'm really missing is customization on the MaterialWindow.
It would be great if there was the possibility of changing the icon template, as the icon I want to show in the title bar isn't the same as the one I want to show in the taskbar.
MetroWindow has IconTemplate and TitleTemplate one can override and I think it would be a useful addition to this library to implement the same.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spiegelp/MaterialDesignExtensions/issues/64?email_source=notifications\u0026email_token=AKRMGNSGSDETLQZLQL4WY2DQYJOYBA5CNFSM4J2A46OKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IADCHMQ",
"url": "https://github.com/spiegelp/MaterialDesignExtensions/issues/64?email_source=notifications\u0026email_token=AKRMGNSGSDETLQZLQL4WY2DQYJOYBA5CNFSM4J2A46OKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IADCHMQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SpoinkyNL** [comment]
Hi, I think something went wrong with your email reply

**Comment by spiegelp** [comment]
@SpoinkyNL Please try the new `MaterialWindow.TitleBarIcon` property of the latest pre-release. Does it fit your needs?

**Comment by SpoinkyNL** [comment]
Works well for my usecase, thank you!
