### ISSUE TITLE
Stepper validation

### ISSUE THREAD

**Issue by kodaniel** [spiegelp/MaterialDesignExtensions#7]
Hi!

Do you have any suggestion how to validate the steps in the stepper?
Basically I have a bunch of viewmodels like in the sample project and I want to validate my properties inside those viewmodels. The question is that how can the validation changes affect to the steps' HasValidationErrors property?

**Comment by spiegelp** [comment]
Hi, there a several ways to hook up validation: 

1. Handle the `Stepper.StepValidation` event: This event will be called if the user navigates to another step. The `StepValidationEventArgs` holds the step to validate. 
```C#
private void StepValidationHandler(object sender, StepValidationEventArgs args)
{
    args.Step.HasValidationErrors = MyValidationMethod(args.Step.Content);
}
```

2. Use the `Stepper.StepValidationCommand` instead of the event. It has a `StepValidationEventArgs` as command parameter. 

3. Use the `IStep.Validate()` method: This method will be called before the `StepValidation` event and command. You can derive from `Step` for each of your steps and override the method. Have a look at the [ValidationStep class](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/ViewModel/StepperViewModel.cs) in the demo. In this scenario, you might also handle the `PropertyChanged` event of your content in your step to trigger the validation with every data change. 

You can choose a way depending on your architecture and coding preferences. I hope this little tutorial helps you.

**Comment by kodaniel** [comment]
Thank you!
Just a short correction for the second solution: the `Stepper.StepValidationCommand` passes the `Step` model itself instead of `StepValidationEventArgs`.

**Comment by spiegelp** [comment]
@kodaniel Thank you for the hint.
