### ISSUE TITLE
SaveFile throws ReferenceKeyNotFoundException

### ISSUE THREAD

**Issue by k0ngen** [spiegelp/MaterialDesignExtensions#8]
Hi,

When I try to implement the SaveFile I get the following exception: "**ResourceReferenceKeyNotFoundException: 'fileSystemEntriesGroupHeaderTemplate' resource not found.**"

I get the following stack trace as well: "**at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)**", without any inner exceptions.

What could be the course of this?

**Comment by spiegelp** [comment]
@k0ngen

Hi, 
I can only guess about the cause, because I do not have your actual code. However, the exception message points to a missing resource. I assume that you forgot to add the styles and templates to your application. Have a look to [App.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/App.xaml) from the demo. The resources will be added to the demo application in line 11. 

If this does not solve you problem, please provide a demo project with your code that I can reproduce the situation on my computer.

**Comment by k0ngen** [comment]
@spiegelp 
Hi again,
Sorry for the late response.
It seems that this error only happens when I try to insert one of the file dialogs into a stepper.

Can you gives this a try?

**Comment by spiegelp** [comment]
@k0ngen 
I can embed a file control inside a stepper or call a file dialog via a button without any problems. So the issue seems to be in your code. You have to provide me a demo project in order to do further debugging.

**Comment by k0ngen** [comment]
@spiegelp
Can you show me how you did that?

**Comment by spiegelp** [comment]
@k0ngen 
I added an example to the Stepper demo. Have a look at the files [StepperControl.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/StepperControl.xaml), [StepperControl.xaml.cs](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/Controls/StepperControl.xaml.cs), [StepperViewModel.cs](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/ViewModel/StepperViewModel.cs), as well as [App.xaml](https://github.com/spiegelp/MaterialDesignExtensions/blob/master/MaterialDesignExtensionsDemo/App.xaml).
