### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by MohammadHadi2031** [spiegelp/MaterialDesignExtensions#97]
Hi. Thanks for your great Controls.

I'm working on a project that all DLL files should be signed. It seems that MaterialDesignExtensions is not signed. Would you mind signing it? Here is the exception:

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='Set connectionId threw an exception.' Line number '7' and line position '9'.
  Source=PresentationFramework

Inner Exception 1:
FileLoadException: Could not load file or assembly 'MaterialDesignExtensions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

VisualStudio 2019
.Net Framework = 4.6.1
WPF application

I really appreciate you.

**Comment by spiegelp** [comment]
@MohammadHadi2031 I will consider to add a strong name for the future. Unfortunately, I have to wait until MaterialDesignThemes.WPF releases the next stable version, because the current version either has no strong name. I saw in the commits, that it will have a strong name by then. 

If you cant wait, you may want to check out the code of the latest stable releases and build it on your own with a strong name.

**Comment by MohammadHadi2031** [comment]
Thanks. I did what you said.

**Comment by numericsguy** [comment]
MaterialDesignThemes.Wpf 3.2.0 has now a strong name.

**Comment by spiegelp** [comment]
The assembly of the latest pre-release v3.3.0-a01 has a strong name.
